[theme]
base                     = "light"
primaryColor             = "#C4FF00"
backgroundColor          = "#E3E3DC"
secondaryBackgroundColor = "#EAEAE4"
textColor                = "#111111"
font                     = "sans serif"

[server]
headless = true
